spring:
  kafka:
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-offset-reset: earliest
      auto-commit-interval: 1000
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      acks: all
      buffer-memory: 20480000
      batch-size: 16384
      retries: 3
    bootstrap-servers: 192.168.16.129
server:
  port: 8686
